name: 🥵 Publish package to the Maven Central Repository 📦🚀

on:
  workflow_dispatch:
    inputs:
      ossrh_username:
        description: 'OSSRH_USERNAME'
        required: true
        type: string
      ossrh_token:
        description: 'OSSRH_TOKEN'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ github.event.inputs.ossrh_username }}
          MAVEN_PASSWORD: ${{ github.event.inputs.ossrh_token }}
